    {
        expect(!EncounterGuideWanted(false,false,200),"alpha38 no GPS outside battle");
        expect(!EncounterGuideWanted(true,true,200),"alpha38 no rival GPS when player leads");
        expect(!EncounterGuideWanted(true,false,99.99f),"alpha38 below 100m no guide");
        expect(EncounterGuideWanted(true,false,100),"alpha38 100m inclusive guide");
        expect(EncounterGuideWanted(true,false,250),"alpha38 distant rival guide");
        expect(!EncounterGuideWanted(true,false,NAN),"alpha38 invalid gap cannot engage guide");
        std::array<unsigned char,0x380> gps{},replacement{};
        alpha38GPS=gps.data();alpha38Engages=alpha38Stops=0;alpha38Success=true;
        g_guide={};g_guideSurface=true;g_guideEngage=&Alpha38Engage;g_guideDisengage=&Alpha38Stop;
        auto** global=reinterpret_cast<void**>(Address(0x0090D8E4));const auto oldGlobal=*global;*global=gps.data();
        put(gps,0,Address(0x00891204));put(gps,0x74,0u);put(gps,0x370,200.f);
        GuideSnapshot snapshot{};
        expect(ReadEncounterGuide(snapshot)&&snapshot.object==gps.data(),"alpha38 native-shaped GPS offsets validated");
        UpdateEncounterGuide(true,false,150,{100,20,200},1000);
        expect(alpha38Engages==1&&g_guide.owned,"alpha38 first eligible sample engages native guide once");
        expect(ReadEncounterGuide(snapshot)&&snapshot.target.x==100&&snapshot.target.y==20&&snapshot.target.z==200,"alpha38 GPS uses canonical XYZ without legacy coordinate permutation");
        UpdateEncounterGuide(true,false,150,{200,20,200},2999);
        expect(alpha38Engages==1,"alpha38 moving target cannot replan before two seconds");
        UpdateEncounterGuide(true,false,150,{200,20,200},3000);
        expect(alpha38Engages==2,"alpha38 latest target is refreshed after bounded interval");
        UpdateEncounterGuide(true,false,150,{210,20,200},5000);
        expect(alpha38Engages==2,"alpha38 under 25m target movement reuses current GPS path");
        UpdateEncounterGuide(true,false,99,{210,20,200},5100);
        expect(alpha38Stops==1&&!g_guide.owned,"alpha38 gap below threshold releases only owned guide");
        // Existing user's guide restored on phase exit, not erased.
        g_guide={};const Vec3 oldTarget{5,6,7};Alpha38Engage(&oldTarget,321.f);
        UpdateEncounterGuide(true,false,180,{500,20,600},10000);
        UpdateEncounterGuide(true,true,180,{500,20,600},11000);
        expect(ReadEncounterGuide(snapshot)&&snapshot.state==2&&snapshot.target.x==5&&snapshot.target.y==6&&snapshot.deviation==321,"alpha38 lead change restores previous GPS target and deviation");
        g_guide={};UpdateEncounterGuide(true,false,180,{500,20,600},12000);
        const Vec3 external{44,55,66};Alpha38Engage(&external,456.f);
        const unsigned before=alpha38Engages,stops=alpha38Stops;
        UpdateEncounterGuide(true,false,180,{700,20,600},15000);StopEncounterGuide(true);
        expect(g_guide.blocked&&!g_guide.owned&&alpha38Engages==before&&alpha38Stops==stops,"alpha38 external destination change revokes lease without overwriting new guide");
        expect(ReadEncounterGuide(snapshot)&&snapshot.target.x==44,"alpha38 external target remains intact");
        g_guide={};UpdateEncounterGuide(true,false,180,{500,20,600},16000);Alpha38Stop();
        const auto cancelCount=alpha38Engages;
        UpdateEncounterGuide(true,false,180,{700,20,600},19000);
        expect(!g_guide.blocked&&g_guide.owned&&alpha38Engages==cancelCount+1,"alpha46 inactive owned guide recovers while battle conditions remain true");
        Alpha38Stop();const auto recoveredCount=alpha38Engages;
        UpdateEncounterGuide(true,false,180,{500,20,600},19001);
        expect(alpha38Engages==recoveredCount&&!g_guide.blocked,"alpha46 repeated auto-completion cannot trigger per-frame path searches");
        UpdateEncounterGuide(true,false,180,{700,20,600},21000);
        expect(alpha38Engages==recoveredCount+1&&g_guide.owned,"alpha46 inactive guide reappears even when rival has not moved 25m");
        const auto savedPrevious=g_guide.previous;put(gps,0x74,99u);
        UpdateEncounterGuide(true,false,180,{800,20,600},23000);
        expect(g_guide.owned&&g_guide.previous.object==savedPrevious.object&&g_guide.previous.target.x==savedPrevious.target.x,"alpha46 transient invalid GPS state preserves restore ownership without calls");
        put(gps,0x74,0u);UpdateEncounterGuide(true,false,180,{800,20,600},23001);
        expect(g_guide.owned&&!g_guide.blocked&&alpha38Engages==recoveredCount+2,"alpha46 valid state after transient read resumes owned guide");
        Alpha38Stop();const auto notWanted=alpha38Engages;
        UpdateEncounterGuide(true,false,99,{800,20,600},25000);
        expect(!g_guide.owned&&alpha38Engages==notWanted+(savedPrevious.state?1u:0u)&&
            ReadEncounterGuide(snapshot)&&snapshot.target.x==savedPrevious.target.x,
            "alpha46 below threshold restores user guide instead of resurrecting rival guide");
        g_guide={};UpdateEncounterGuide(true,false,180,{500,20,600},20000);
        put(replacement,0,Address(0x00891204));put(replacement,0x74,2u);put(replacement,0x370,200.f);*global=replacement.data();
        const auto replaceStops=alpha38Stops;StopEncounterGuide(true);
        expect(alpha38Stops==replaceStops&&!g_guide.owned,"alpha38 replaced GPS instance is never modified");
        *global=gps.data();g_guide={};put(gps,0x74,0u);alpha38Success=false;
        UpdateEncounterGuide(true,false,180,{500,20,600},24000);
        expect(!g_guide.owned,"alpha38 failed native search drops lease and leaves battle untouched");
        const auto failedCalls=alpha38Engages;
        UpdateEncounterGuide(true,false,180,{700,20,600},25000);
        expect(alpha38Engages==failedCalls,"alpha38 failed path has bounded retry backoff");
        alpha38Success=true;g_guide={};put(gps,0x74,0u);
        UpdateEncounterGuide(true,false,180,{500,20,600},28000);
        const auto beforeWorldExit=alpha38Engages;StopEncounterGuide(false);
        expect(alpha38Engages==beforeWorldExit&&!g_guide.owned,"alpha38 world exit does not replan previous GPS route");
        put(gps,0,0u);expect(!ReadEncounterGuide(snapshot),"alpha38 wrong GPS vtable rejected");
        put(gps,0,Address(0x00891204));put(gps,0x74,99u);expect(!ReadEncounterGuide(snapshot),"alpha38 invalid GPS state rejected");
        *global=oldGlobal;g_guide={};g_guideSurface=false;g_guideEngage=nullptr;g_guideDisengage=nullptr;
    }
