    {
        const auto settings=g_settings;
        VehicleSnapshot player{},cop{},rival{};
        player.pointer=reinterpret_cast<void*>(1);cop.pointer=reinterpret_cast<void*>(2);
        rival.pointer=reinterpret_cast<void*>(3);rival.vehicleKey=123;
        cop.driverClass=2;rival.driverClass=kDriverRacer;
        cop.position={50,0,0};rival.position={100,0,0};rival.speed=20;
        ManagedRacer managed{};managed.pointer=rival.pointer;managed.vehicleKey=123;
        managed.simable=reinterpret_cast<void*>(4);managed.ageSeconds=6;
        auto valid=[&](){return PolicePairEligible(player,cop,rival,managed);};
        expect(valid(),"alpha41 nearby managed racer is candidate");
        for(unsigned driver:{0u,1u,3u,4u,6u}) {cop.driverClass=driver;expect(!valid(),"alpha41 excludes humans traffic racers and other drivers as cops");}cop.driverClass=2;
        for(unsigned driver:{0u,1u,2u,4u,6u}) {rival.driverClass=driver;expect(!valid(),"alpha41 only racer-class targets");}rival.driverClass=3;
        rival.pointer=player.pointer;expect(!valid(),"alpha41 no player targets");rival.pointer=managed.pointer;
        ++rival.vehicleKey;expect(!valid(),"alpha41 recycled vehicle identity rejected");--rival.vehicleKey;
        managed.missingSeconds=.05f;expect(!valid(),"alpha41 missing racer rejected");managed.missingSeconds=0;
        managed.ageSeconds=4.99f;expect(!valid(),"alpha41 freshly constructing racer excluded");managed.ageSeconds=5;
        rival.speed=0;expect(!valid(),"alpha41 parked racer excluded");rival.speed=std::numeric_limits<float>::quiet_NaN();expect(!valid(),"alpha41 NaN speed rejected");rival.speed=20;
        rival.position={201,0,0};expect(!valid(),"alpha41 detection bound 150m");rival.position={200,0,0};expect(valid(),"alpha41 150m inclusive");
        cop.position={351,0,0};rival.position={400,0,0};expect(!valid(),"alpha41 distant patrol excluded");cop.position={350,0,0};expect(valid(),"alpha41 350m inclusive");
        rival.position={0,0,0};cop.position={0,0,151};expect(!valid(),"alpha41 distance includes all axes");
        cop.position={0,0,0};rival.position={0,151,0};expect(!valid(),"alpha41 vertical or permuted axis not ignored");
        rival.position={0,0,0};g_settings.populationRadiusMeters=100;rival.position={101,0,0};expect(!valid(),"alpha41 outside current population radius excluded");
        g_settings=settings;
        const auto oldHash=g_patrolGoalHash;g_patrolGoalHash=123;
        PatrolState patrol{};patrol.goal=123;expect(PoliceIdle(patrol),"alpha41 clean patrol eligible");
        patrol.inPursuit=1;expect(!PoliceIdle(patrol),"alpha41 in-pursuit cop untouched");patrol.inPursuit=0;
        patrol.pursuit=1;expect(!PoliceIdle(patrol),"alpha41 pursuit reference prevents takeover");patrol.pursuit=0;
        patrol.targetValid=1;expect(!PoliceIdle(patrol),"alpha41 pending native target preserved");patrol.targetValid=0;
        patrol.targetSimable=1;expect(!PoliceIdle(patrol),"alpha41 stale or reserved target not overwritten");patrol.targetSimable=0;
        patrol.goal=456;expect(!PoliceIdle(patrol),"alpha41 roadblocks support and flee goals excluded");
        g_patrolGoalHash=oldHash;
        // Read-only synthetic native CopCar layout, including target and pursuit.
        std::array<std::uint8_t,0x800> aiStorage{};
        std::array<std::uint8_t,0x100> vehicleStorage{};
        std::array<std::uint8_t,0x40> targetStorage{};
        auto put=[](void* p,std::size_t off,std::uintptr_t value){std::memcpy(static_cast<std::uint8_t*>(p)+off,&value,sizeof(value));};
        put(vehicleStorage.data(),0,Address(kIVehicleVtable));
        put(vehicleStorage.data(),0x54,reinterpret_cast<std::uintptr_t>(aiStorage.data()+0x4C));
        put(aiStorage.data(),0,Address(0x00892560));put(aiStorage.data(),0x4C,Address(0x00892480));
        put(aiStorage.data(),0x758,Address(0x008923E8));put(aiStorage.data(),0xA0,reinterpret_cast<std::uintptr_t>(targetStorage.data()));
        put(aiStorage.data(),0xC4,321);cop.pointer=vehicleStorage.data();cop.driverClass=2;
        expect(ReadPatrol(cop,patrol)&&patrol.goal==321&&!patrol.pursuit,"alpha41 verified CopCar layout read");
        put(aiStorage.data(),0xBC,456);aiStorage[0x760]=1;targetStorage[0x2C]=1;put(targetStorage.data(),0x1C,789);
        expect(ReadPatrol(cop,patrol)&&patrol.pursuit==456&&patrol.inPursuit&&patrol.targetValid&&patrol.targetSimable==789,"alpha41 pursuit and target distinguish actual chase from request");
        put(aiStorage.data(),0x4C,Address(0x00891FF8));expect(!ReadPatrol(cop,patrol),"alpha41 helicopter subtype rejected");
        put(aiStorage.data(),0x4C,Address(0x00892480));put(aiStorage.data(),0xA0,0);expect(!ReadPatrol(cop,patrol),"alpha41 missing target fails closed");
        g_policeTimer=8;g_policeLogTimer=3;g_policeAttempts=5;g_policeRequests=2;
        g_policeFaulted=true;ResetBackgroundPolice();
        expect(g_policeTimer==0&&g_policeLogTimer==0&&g_policeAttempts==0&&g_policeRequests==0,"alpha41 world reset clears counters only");
        expect(g_policeFaulted,"alpha41 fault stays disabled across safehouse transitions");g_policeFaulted=false;
        const bool oldSurface=g_policeSurface;g_policeSurface=false;
        UpdateBackgroundPolice(player,{},1);expect(g_policeAttempts==0,"alpha41 invalid surface no native access");g_policeSurface=oldSurface;
    }
